---
- name: yum install epel-release
  yum:
    name: epel-release
    state: latest

- name: yum installed of basic software 
  yum:
    name: "{{ item }}"
    state: latest
  with_items: 
    - gcc
    - automake
    - autoconf 
    - libtool 
    - make 
    - gcc-c++ 
    - glibc 
    - libxslt-devel 
    - libjpeg 
    - libjpeg-devel 
    - libpng 
    - libpng-devel 
    - freetype 
    - freetype-devel 
    - libxml2
    - libxml2-devel 
    - zlib
    - zlib-devel 
    - glibc 
    - glibc-devel 
    - glib2 
    - glib2-devel 
    - bzip2 
    - bzip2-devel 
    - ncurses 
    - ncurses-devel 
    - curl 
    - curl-devel 
    - e2fsprogs 
    - e2fsprogs-devel 
    - krb5-devel 
    - libidn 
    - libidn-devel 
    - openssl 
    - openssl-devel 
    - pcre 
    - pcre-devel 
    - libmcrypt 
    - libmcrypt-devel 
    - cmake
    - net-snmp-devel
    - MySQL-python
    - mysql-devel
