---
- name: create zabbix group
  group:
    name: zabbix
    state: present

- name: create zabbix user
  user:
    name: zabbix
    group: zabbix
    createhome: no
    shell: /sbin/nologin
    state: present

- name: create unarchive directories
  file:
    path: "{{ unarchive_dir }}"
    state: directory
    recurse: yes

- name: copy and unarchive zabbix engine
  unarchive:
    src: "{{ zabbix_release }}"
    dest: "{{ unarchive_dir }}"

- name: Configure zabbix_server
  shell: "./configure --prefix={{ zabbix_install_dir }} --enable-server --enable-proxy --enable-agent --with-mysql={{ mysql_config_dir }} --with-net-snmp --with-libcurl"
  args:
    chdir: "{{ unarchive_dir }}/zabbix-3.0.10"

- name: make zabbix_server
  shell: "make"
  args:
    chdir: "{{ unarchive_dir }}/zabbix-3.0.10"

- name: make install zabbix_server
  shell: "make install"
  args:
    chdir: "{{ unarchive_dir }}/zabbix-3.0.10"

- name: create database
  mysql_db:
    name: zabbix
    encoding: utf8
    state: present

- name: create user
  mysql_user:
    name: zabbix
    password: zabbix
    priv: 'zabbix.*:ALL'
    state: present

- name: import sql
  shell: "mysql -uzabbix -pzabbix zabbix < {{ item }}"
  args:
    chdir: "{{ unarchive_dir }}/zabbix-3.0.10/database/mysql"
  with_items:
    - schema.sql
    - images.sql
    - data.sql

- name: Create zabbix log  Directories
  file:
    path: "{{ zabbix_log_dir }}"
    state: directory
    recurse: yes
    owner: zabbix
    group: zabbix

- name: set zabbix link
  file:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
    mode: 0655
  with_items:
    - { src: '{{ zabbix_install_dir }}/etc/',dest: '/etc/zabbix' }
    - { src: '{{ zabbix_install_dir }}/bin/zabbix_sender',dest: '/usr/local/bin/zabbix_sender' }
    - { src: '{{ zabbix_install_dir }}/bin/zabbix_get',dest: '/usr/local/bin/zabbix_get' }
    - { src: '{{ zabbix_install_dir }}/sbin/zabbix_server',dest: '/usr/local/sbin/zabbix_server' }
    - { src: '{{ zabbix_install_dir }}/sbin/zabbix_agentd',dest: '/usr/local/sbin/zabbix_agentd' }
    - { src: '{{ zabbix_install_dir }}/sbin/zabbix_proxy',dest: '/usr/local/sbin/zabbix_proxy' }

- name: copy zabbix agentd init.d
  template:
    src: zabbix_agentd.j2
    dest: "/etc/init.d/zabbix-agentd"
    mode: 0655

- name: copy zabbix server init.d
  template:
    src: zabbix_server.j2
    dest: "/etc/init.d/zabbix-server"
    mode: 0655

- name: copy zabbix server conf
  template:
    src: zabbix_server.conf.j2
    dest: "{{ zabbix_install_dir }}/etc/zabbix_server.conf"
    mode: 0655

- name: copy zabbix agentd conf
  template:
    src: zabbix_agentd.conf.j2
    dest: "{{ zabbix_install_dir }}/etc/zabbix_agentd.conf"
    mode: 0655

- name: copy zabbix php page
  shell: "cp -r {{ unarchive_dir }}/zabbix-3.0.10/frontends/php/ {{ nginx_install_dir }}/html/zabbix"

- name: chown zabbix php page
  file:
    path: "{{ nginx_install_dir }}/html/zabbix"
    state: directory
    owner: www
    group: www
    recurse: yes

- name: start zabbix server
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - zabbix-server
    - zabbix-agentd
